"""2. Agregar 4 Objetos nuevos a tu lista (append)"""
lista_1 = [
    "GESTIÓN DEL CONOCIMIENTO",
    "GESTIÓN DE LA INFORMACIÓN DIGITAL",
    "GESTIÓN DE PROYECTOS DE TI",
    "TRANSFORMACIÓN DIGITAL",
    "DIRECCIÓN DE TESIS I",
    "SEMINARIO DE INVESTIGACIÓN I"
]
lista_1.append("TÓPICOS AVANZADOS EN INVESTIGACIÓN CIENTÍFICA")
lista_1.append("DIRECCIÓN DE TESIS II")
lista_1.append("SEMINARIO DE INVESTIGACIÓN II")
lista_1.append("MACHINE LEARNING Y BIG DATA")
print(lista_1)